sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

env:
  - THEME_DIR=web/app/themes/thepoliticalsage

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $THEME_DIR/bower_components
    - $THEME_DIR/node_modules

before_install:
  - cd $THEME_DIR

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
